### ISSUE TITLE
disabling `using_<source_table>` doesn't remove table from sources

### ISSUE THREAD

**Issue by ericalouie** [fivetran/dbt_zendesk_source#10]
Hi team!

We added this package to our dbt project and disabled `user_tags` as we don't have this enabled on our account and this table doesn't exist in our warehouse (see configuration below)
![image](https://user-images.githubusercontent.com/20780760/116467845-26f59700-a83e-11eb-8ef0-9357882f6dc5.png)

However, it looks like in the `src_zendesk.yml` file, the `user_tag` table is still being counted when we run a `dbt source snapshot-freshness` command.
![image](https://user-images.githubusercontent.com/20780760/116468007-57d5cc00-a83e-11eb-8664-2feda28e5a9a.png)

We were able to solve this issue by explicitly disabling `user_tags` in a `source` configuration block (see image below), but figured I'd bring this to your attention :) 
![image](https://user-images.githubusercontent.com/20780760/116468067-6ae89c00-a83e-11eb-8731-0b0cf25b3c21.png)

**Comment by fivetran-kristin** [comment]
Hey @ericalouie, This is super interesting, thanks for sharing!

I'm thinking we should just incorporate this change in our package's source config block so it disables the freshness tests for users automatically.
