### ISSUE TITLE
[Feature] Add phone to stg_zendesk__user

### ISSUE THREAD

**Issue by trunsky** [fivetran/dbt_zendesk_source#39]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Looks like the staging models are a bit out of date with what fields fivetran actually replicates from Zendesk. This is just one I've noticed that would be helpful, but there are others. 

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by trunsky** [comment]
> hi @trunsky! Yeah phone definitely makes sense to include. Curious to hear about the other missing fields you think would be helpful (in `user` or other tables)
> 
> Also, if you're using the zendesk [transform](https://github.com/fivetran/dbt_zendesk) package, do you envision `phone` being passed to any end models there? Or is just having it in the staging user model sufficient?

Hello @fivetran-jamie! I just started using it yesterday to take advantage of the SLA model. We had some existing reporting on tickets I was going to cut over to using it as well, and that is just one field I noticed was missing. For us, it would be helpful on the ticket related models.

**Comment by fivetran-jamie** [comment]
Cool good to know! 

For the time being, I am going to leave this feature request open to allow other members of the community to chime in if they would find this field helpful. If more community members engage we will happily accept this feature into an upcoming sprint.

**Comment by fivetran-jamie** [comment]
hey @trunsky 👋 included this update in the most recent release, [v0.11.1](https://github.com/fivetran/dbt_zendesk_source/releases/tag/v0.11.1) 

going to close this issue, but i know you mentioned potentially adding other fields as well. please feel free to open another issue if there are specific ones you'd want to see added too!
