### ISSUE TITLE
[Bug] Incorrect "agent replies" and "agent comments" metrics in zendesk__ticket_metrics

### ISSUE THREAD

**Issue by nicksimba** [fivetran/dbt_zendesk_source#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The metrics 'total_agent_replies' and 'count_agent_comments' in the zendesk__ticket_metrics model are incorrect when compared with what Zendesk uses for their analytics. It looks like the metrics in the Fivetran model ignores "agent comments" from users who were agents at the time the comment was left on a ticket, but who no longer are agents (if they left the business). 

In my view these should still be counted as 'agent comments', and this is how Zendesk treats them in their own analytics tool. Otherwise, this makes historical analysis incorrect as these metrics will be skewed based on whether a historical ticket was handled by someone who is still an agent today, or by someone who has left the business and therefore no longer an agent.

### Expected behavior

In my view the metrics should count comments made by ex-agents who were agents at the time of the comment. Zendesk is able to provide this detail through their Data API endpoints we received through our previous data movement platform so I assume there must be an audit trail somewhere in the schema to track when users changed roles.

### dbt Project configurations

Running the Fivetran dbt transformations as they come

### Package versions

-

### What database are you using dbt with?

snowflake

### dbt Version

Running on the latest dbt version 1.7

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by nicksimba** [comment]
Package version: ![image](https://github.com/fivetran/dbt_zendesk_source/assets/119435491/4d1f7853-7258-4b90-9ae8-0619885a526f)

**Comment by nicksimba** [comment]
I've been investigating various time-based metrics from this model which are coming through with incorrect values compared to our Zendesk portal, and have a suspicion this might also be related to the 'agent' status of a used. I've gone through several example tickets where the time-based metrics are incorrect, and they all contain comments by agents who are no longer with the business (and therefore not active agents at the present time). By contrast, all the tickets I've tested where the time-based metrics are coming through correctly, are tickets where the only agents who handled the ticket, are still agents today.

I see this dependency table which the 'zendesk__ticket_metrics' model is reliant on 'end_user_comment_created_at', 'agent_responded_at'. So presumably if users who were agents at the time of the ticket, but the model is counting them as end-users, this will be causing incorrect calculations?

![image](https://github.com/fivetran/dbt_zendesk_source/assets/119435491/80f71a37-4492-459f-bb4b-a6fa779fe95e)

**Comment by fivetran-avinash** [comment]
Hi @nicksimba , thanks for reaching out and noticing this issue. This is definitely a limitation of Zendesk's data, as deactivated agents do get reclassified as users.  This is a limitation on the connector as we do not sync user history data at this time. 

I notice your configuration is "Running the Fivetran dbt transformations as they come". Do you happen to be using Quickstart? If so, the solution below will not work as you cannot configure variables in Quickstart.

If you aren't, [we have a workaround we recently introduced](https://github.com/fivetran/dbt_zendesk_source/releases/tag/v0.10.1)!  You can reclassify deactivated agents back from `end-user`. [You can see the instructions in the README here](https://github.com/fivetran/dbt_zendesk_source/blob/main/README.md#mark-former-internal-users-as-agents).  You can see this logic[ in action in the `stg_zendesk__user` table](https://github.com/fivetran/dbt_zendesk_source/blob/main/models/stg_zendesk__user.sql).
So you would use whatever specific criteria you need to reclassify your deactivated agents back from `end-user` to `agents` by set this variable in your `dbt_project.yml`.

```

# dbt_project.yml
vars:
  zendesk_source:
    internal_user_criteria: "[INSERT YOUR SQL FILTER HERE TO GET THE FORMER AGENTS]"

```

So I would test that out if you have the ability to modify your `dbt_project.yml`. If you are using Quickstart, this will not be possible at this time, and you will have to wait until we add variable configuration (which we do have on our roadmap). 

Let me know if this approach makes sense!

**Comment by nicksimba** [comment]
Hey Avinash,

Thanks for your reply and great to know there’s a workaround in place for this, we’ll look into this and see if this works for us.

Is there a plan to get access to user history data on the roadmap, or do Zendesk not offer an endpoint for this at the moment? It’s a crucial gap in data.

Thanks,
Nick

**Comment by fivetran-avinash** [comment]
Hi @nicksimba, awesome, looking forward to you testing and seeing if this variable configuration works for your purposes!

Thanks for the request! This is indeed something that has been requested a few times. The next best step would be to add your thoughts to [this open feature request in our Fivetran Support Portal,](https://support.fivetran.com/hc/en-us/community/posts/1500000989682-Connector-Improvement-Zendesk-user-role-history) and explain why this would be important. Agreed that it would make your job a lot easier in determining who is an agent or an admin!

**Comment by fivetran-avinash** [comment]
Hi @nicksimba , I believe the above mentioned approach should work for your purposes. The Support Portal would be the next best step for you if you want to proceed further.  I will close this issue out.

Let me know if you have any questions!
