### ISSUE TITLE
update required dbt version to allow v0.19.0

### ISSUE THREAD

**Issue by MarkMacArdle** [fivetran/dbt_zendesk_source#6]
Same as an issue I raised in the stripe package [here](https://github.com/fivetran/dbt_stripe/issues/6). 

If the requirements could be updated to allow dbt v0.19 that'd be great.

**Comment by fivetran-kristin** [comment]
Hey @MarkMacArdle! We're working on pushing some pretty big changes to this package, including this compatibility. I expect we'll be releasing a new version of this package in the next few days.

Until that happens, can you run dbt using the following: `dbt run --no-version-check`?

**Comment by fivetran-kristin** [comment]
Fixed with release v0.2.0!
